#ifndef @PROJECT_NAME@_CONFIG_H
#define @PROJECT_NAME@_CONFIG_H

#cmakedefine  QT_LIB_ENABLE
#cmakedefine  GLFW_LIB_ENABLE
#cmakedefine  VK_USE_PLATFORM_XCB_KHR
#cmakedefine  VK_USE_PLATFORM_WIN32_KHR

#cmakedefine SHADER_DIRECTORY "@SHADER_DIRECTORY@"
#cmakedefine MODELS_DIRECTORY "@MODELS_DIRECTORY@"
#cmakedefine DATA_DIRECTORY "@DATA_DIRECTORY@"
#cmakedefine VULKAN_VALIDATION_LAYERS
#cmakedefine LOGGING_DIRECTORY "@LOGGING_DIRECTORY@"

#endif /* @PROJECT_NAME@_CONFIG_H */
