include(FindPackageHandleStandardArgs)

################################################################################
#Look for packages
################################################################################
if(UNIX)
    find_package(ECM REQUIRED NO_MODULE)
    set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${ECM_FIND_MODULE_DIR})
endif()

if(QT_LIB_ENABLE)
    if(MSVC)
        set(CMAKE_PREFIX_PATH "${QT_PATH}/msvc2019_64/lib/cmake" ${CMAKE_PREFIX_PATH})
        set(QT_LIB_TYPE_PATH "/msvc2019_64")
    elseif(MINGW)
        set(CMAKE_PREFIX_PATH "${QT_PATH}/mingw81_64/lib/cmake" ${CMAKE_PREFIX_PATH})
        set(QT_LIB_TYPE_PATH "/mingw81_64")
    endif()
    find_package(Qt5 COMPONENTS Core Widgets Charts REQUIRED)
    if(UNIX)
        find_package(Qt5X11Extras REQUIRED)
        find_package(XCB REQUIRED)
    endif()
endif()

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/CMakeModules/finds/")

if(NOT QT_LIB_ENABLE)
    find_package(GLFW3 REQUIRED)
    if(NOT GLFW3_FOUND)
        message(WARNING "Not found glfw library make shure you add GLFW3_ROOT path")
    else()
        if(WIN32)
            if(MINGW)
                message(STATUS "GLFW3 is " ${GLFW3_INCLUDE_DIR} " " ${GLFW3_LIBRARY})
            elseif(MSVC)
                if(NOT GLFW3_ROOT)
                    set(GLFW3_ROOT "C:/GLFW")
                endif()
                set(GLFW3_LIBRARY "${GLFW3_ROOT}/lib-vc2022/glfw3.lib")
                message(STATUS "GLFW3 is " ${GLFW3_INCLUDE_DIR} " " ${GLFW3_LIBRARY})
            endif()
            include_directories(${GLFW3_INCLUDE_DIR})
        endif()
    endif()
endif()

find_package(GLM CONFIG)
if(NOT GLM_FOUND)
    message(WARNING "Not found glm library make shure you add GLM_ROOT path")
else()
    if(WIN32)
        if(MINGW)
            include_directories(${GLM_ROOT})
        endif()
    endif()
endif()

find_package(Vulkan REQUIRED)
if(NOT Vulkan_FOUND)
    message(WARNING "Not found glm library make shure you add Vulkan_ROOT path")
else()
    if(WIN32)
        message(STATUS $ENV{VULKAN_SDK})
        include_directories($ENV{VULKAN_SDK}/include)
    endif()
endif()

set(LOGGER_ROOT ${${PROJECT_NAME}_DEPENDENCIES_PATH}/Logger)
set(IMGUI_ROOT ${${PROJECT_NAME}_DEPENDENCIES_PATH}/imgui)
set(KHR_ROOT ${${PROJECT_NAME}_DEPENDENCIES_PATH}/KHR)
set(PHYSICS_REPO_ROOT ${${PROJECT_NAME}_DEPENDENCIES_PATH}/JoltPhysics)
