#file: noinspection YAMLSchemaValidation
name: sky engine build

#run on push
on: push

jobs:
  build:
    name: build
    runs-on: self-hosted
    steps:
    - name: checkout and build
      uses: actions/checkout@v2
      run: cmake -B build .
